/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    // Pin here (not via a separate buildSrc/settings + catalog) so IntelliJ models classic buildSrc reliably.
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.21")
}
